### ISSUE TITLE
 Norton blocks plugin

### ISSUE THREAD

**Issue by uChip** [FlyingSamson/SpaceMouseTool#11]
Window 10, Cura 5.1.0, SpaceMouseTool 1.3.0

Download zip file.
Extract SpaceMouseTool folder to Cura plugins folder.
Launch Cura.
Norton throws error message and removes files from SpaceMouseTool/lib
![NortonErrorMsg](https://user-images.githubusercontent.com/4139830/190926087-549baf26-1a60-4ce5-b961-db33cbaa4a45.jpg)
Cura runs but gives error dialog that plugin did not load

**Comment by FlyingSamson** [comment]
I use Windows only very rarely and do not really know what I am supposed to do about Norton identifying it as a threat without even telling what exactly it dislikes about the python lib. I certainly did not put in any male ware into that lib, so I would suspect this to be a false positive. If the error persists maybe one should report this to Norton, then either they can analyze the file properly and tell what the problem is, or white-list it or something.

**Comment by uChip** [comment]
I agree that it's nothing malicious and probably a false positive, but sometimes a virus still slips in so I thought I would flag it.  Researching some more on the "Insight Network Threat" I assume that Norton is flagging it just because there are few reports of it being used.  Based on that research and your comment I overrode the block (clicked Restore and whitelisted the lib on my machine).  Cura now launches and the plugin loads.  Some of the axes are wrong but I will file that as a separate issue after I research it some more.  Thanks for responding and thanks for the plugin.
