### ISSUE TITLE
Where to get si.h and siapp.h?

### ISSUE THREAD

**Issue by Fedr** [FlyingSamson/SpaceMouseTool#12]
I am sorry if I ask something trivial, but in your instruction it is said that for Windows:

> you will need the 3Dconnexion SDK which is available in the developer section of the 3Dconnexion website (requires you to create an account).

I did so, created an account there and downloaded `3DxWare_SDK_v4-0-2_r17624`. But I do not see `si.h` and `siapp.h` inside, which is required to build your plugin. Could you please clarify where to get them?

**Comment by FlyingSamson** [comment]
It has been a while since I implemented the Windows support. If I remember correctly there where two types of API provided by 3D Connexion. I used the native API using the nativ Windowhandler HWND.

On my system those headers are located in `Program Files (x86)\3Dconnexion\3DxWare SDK\Inc` but it has been years since I downloaded and installed the SDKs. The `3DxWareVersionNumbers.h` lists
```
#define _3DXWINCORE_VERSION_MAJOR 17
#define _3DXWINCORE_VERSION_MINOR 5
#define _3DXWINCORE_VERSION_MICRO 5
#define _3DXWINCORE_VERSION_BUILD_NUMBER 18050
```
and a copyright of 2018. So maybe you can find an SDK version from back than, or maybe that low level SDK is only available in the 32bit download?

All this aside, you did realize, that you will only need the SDK if you want to compile the plugin from source, right? That  is, if your only want to use the plugin in Cura, you do not have to do all this.

**Comment by FlyingSamson** [comment]
As far as I can remember the SDK back then also was an `*.exe` that needed installation. Not sure why it is now only a folder containing the sources...

**Comment by Fedr** [comment]
I see, thanks a lot!
I found these files in another GitHub project: https://github.com/solvespace/solvespace/tree/master/extlib/si
